[project]
name = "ai-blogger-backend-test"
version = "0.1.0"
description = ""
authors = [
    {name = "Артамонов Алексей Викторович",email = "artamonov008@yandex.ru"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry]
packages = [{include = "ai_blogger_backend_test", from = "src"}]

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
